switch to crc to avoid lazy_static
fix:

error[E0432]: unresolved import `core::sync::atomic::AtomicBool`
 --> /home/nim/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.5.2/src/mutex.rs:1:26
  |
1 | use core::sync::atomic::{AtomicBool, Ordering, spin_loop_hint as cpu_relax};
  |                          ^^^^^^^^^^ no `AtomicBool` in `sync::atomic`

error[E0432]: unresolved import `core::sync::atomic::AtomicUsize`
 --> /home/nim/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.5.2/src/rw_lock.rs:8:55
  |
8 | use core::sync::atomic::{spin_loop_hint as cpu_relax, AtomicUsize, Ordering};
  |                                                       ^^^^^^^^^^^ no `AtomicUsize` in `sync::atomic`

error[E0432]: unresolved import `core::sync::atomic::AtomicUsize`
 --> /home/nim/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.5.2/src/once.rs:2:26
  |
2 | use core::sync::atomic::{AtomicUsize, Ordering, spin_loop_hint as cpu_relax};
  |                          ^^^^^^^^^^^ no `AtomicUsize` in `sync::atomic`